### ISSUE TITLE
Multiple accounts may fails in github actions

### ISSUE THREAD

**Issue by futuretech6** [AsterNighT/sisyphus#3]
When I have set 2 accounts in github acctions, there is possibility that the second account will fail to connect to zju's server like [this](https://github.com/FUTURETECH6/sisyphus/runs/6416837146?check_suite_focus=true#step:5:28). I don't know if it's because of github server's connection or else. Adding a sleep may help?

**Comment by futuretech6** [comment]
btw, it's ok to hitcard both accounts without connection error using local machine.

**Comment by AsterNighT** [comment]
I don't see a good reason for the program to fail in github actions only. Maybe it's a network issue. I tried using github actions to submit two reports and the first attempt suceeded while the second one failed. I suggest it is some mysterious ZJU firewall blocking foreign connections. 
I'm afraid there won't be much we can do. Like you said, put a time gap in between two attempts may work. But to achieve this, using a fixed sleep in code does not seem to be a good idea. I'll look into it.

**Comment by AsterNighT** [comment]
Unfortunately I haven't found a clue concerning the firewall limit. I assume a 3 min delay should be enough.
