### ISSUE TITLE
oldInfo改名了

### ISSUE THREAD

**Issue by futuretech6** [AsterNighT/sisyphus#8]
response里现在没有这个东西了，发现一个类似的东西叫`def`

**Comment by AsterNighT** [comment]
我不理解。我去确认了一下，似乎并没有变化。

**Comment by futuretech6** [comment]
前几天测试的时候确实没了，今天看又有这个东西了（但是即使填报了一次值也是`{}`）

**Comment by futuretech6** [comment]
现在只能在getInfo中手动填入id和uid

**Comment by AsterNighT** [comment]
我想你需要提供一下你的网页源代码，我在测试中无法复现这个问题。

**Comment by futuretech6** [comment]
`getInfo`函数中`const text = await reportPage.text();`获得的`text`的`/oldInfo: ({.+}),/ `一栏有概率是`oldInfo : {},`，这会影响到uid与id的获取导致程序抛出`'Info format changed'`。临时的解决方案是跳过这一步骤直接手动填入id与uid（但是这样就不能多人打卡了）

我认为这不是本地脚本的问题，而是healthreport的行为异常问题，我前几天一直会遇到这个问题，今天又正常了。
